import { expect } from 'chai';
import isLength from "../src/isLength.js";

/*
* These tests are generated by Copilot (ChatGPT-5 mini) AI based on the
* instruction on instructionsToAI.txt.
* 
* Tester: Olivia Härkönen
*/

describe('isLengthAI', () => {
    it('valid max safe integer is length', () => {
        expect(isLength(Number.MAX_SAFE_INTEGER)).to.equal(true);
    });

    it('zero is length', () => {
        expect(isLength(0)).to.equal(true);
    });

    it('negative number is not length', () => {
        expect(isLength(-1)).to.equal(false);
    });

    it('non-integer number is not length', () => {
        expect(isLength(3.14)).to.equal(false);
    });

    it('number greater than MAX_SAFE_INTEGER is not length', () => {
        expect(isLength(Number.MAX_SAFE_INTEGER + 1)).to.equal(false);
    });

    it('non-number value is not length', () => {
        expect(isLength('3')).to.equal(false);
    });
});